# application.yml
server:
    port: 8081 # or your preferred port

spring:
  application:
    name: dns-server-app


eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
