# application.yml
server:
    port: 8081 # or your preferred port

spring:
  application:
    name: dns-server-app


client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true 
