# Default port for Eureka Servers

spring:
  application:
    name: eureka-server-app

server:
  port: 8761
# Prevents the eureka server from registering with other servers
# https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-eureka-server.html#spring-cloud-eureka-server-standalone-mode

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false